### ISSUE TITLE
Colors not showing up in Windows 10

### ISSUE THREAD

**Issue by KrishKayc** [t0xic0der/prudence#11]
The command line doesn't show the colors in windows 10 as it does in linux. Reason is that colors used are ANSI escape codes and windows won't support it.  

Current output in windows:

![Screenshot from 2020-10-15 18-27-58](https://user-images.githubusercontent.com/4170753/96158842-90acf400-0f31-11eb-9be3-c2ca94cf5310.png)

**Comment by KrishKayc** [comment]
@t0xic0der Can you please assign this to me? I

In windows 10, there is a way to enable ANSI escaped values by setting some console flag called ENABLE_VIRTUAL_TERMINAL_PROCESSING.

If, we enable this flag from the app, there is no need to change any code inside colorformat package

**Comment by KrishKayc** [comment]
Have created PR for this. https://github.com/t0xic0der/prudence/pull/13

**Comment by gridhead** [comment]
> @t0xic0der Can you please assign this to me? I
> 
> In windows 10, there is a way to enable ANSI escaped values by setting some console flag called ENABLE_VIRTUAL_TERMINAL_PROCESSING.
> 
> If, we enable this flag from the app, there is no need to change any code inside colorformat package

Sure. I have assigned this to you and am in the process of reviewing your pull request.
