### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/prudence#4]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by KrishKayc** [comment]
@t0xic0der Hey, I have created PR for this.  https://github.com/t0xic0der/prudence/pull/10.

**Comment by gridhead** [comment]
Thanks. I am looking into your pull request now. You are requested to kindly ask for issue assignment before getting to work on it as that could potentially save you a lot of time, should the issue has already been worked upon.

Feel free to leave a star at the repository if you found it helpful.
