### ISSUE TITLE
Display time taken to address request

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/prudence#5]
Let the users know the time taken to address their request for logistical purposes.

**Comment by pedroandrade** [comment]
Hi @t0xic0der, I'd like to pick this one, could you assign to me?

**Comment by gridhead** [comment]
Cool. I am assigning you this issue.

**Comment by gridhead** [comment]
Closed #5 via #14.

Thank you @pedroandrade for your wonderful contributions. :smile:
