### ISSUE TITLE
Test application compatibility with Windows 10

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/prudence#8]
The following must be tested to complete the following QA check
- [ ] Testing command-line arguments in Command Prompt
- [ ] Testing command-line arguments in Powershell

**Comment by KrishKayc** [comment]
@t0xic0der  I can test this, can you assign this to me?

**Comment by KrishKayc** [comment]
@t0xic0der **Colors won't appear** as windows doesn't support **ANSI escape codes.**

![Screenshot from 2020-10-15 18-27-58](https://user-images.githubusercontent.com/4170753/96130025-fd65c580-0f14-11eb-9f0c-70570bad9429.png)

**Comment by gridhead** [comment]
Alright. Thanks for listing this. Could you please create an issue regarding this so that colors can be worked upon dedicatedly for Windows 10?

**Comment by KrishKayc** [comment]
Sure, I will create an issue for this.

**Comment by KrishKayc** [comment]
@t0xic0der  Can we close this as a new issue is posted and addressed by https://github.com/t0xic0der/prudence/pull/13

**Comment by gridhead** [comment]
I have tagged a couple of folks but none of them are willing to pick up the review lol. Let me review your PR and then, merge it - which would automatically close this issue. :smile:

**Comment by KrishKayc** [comment]
okay :-)

**Comment by KrishKayc** [comment]
@t0xic0der Any updates?

**Comment by gridhead** [comment]
Hi @KrishKayc, I took a break for almost about a week and came back. I have resolved the merge conflicts in https://github.com/t0xic0der/prudence/pull/13/ and proceeding into review.

**Comment by gridhead** [comment]
I have commented the code you added after the merge because even though it works on Windows, it breaks the compatibility on GNU/Linux. Do take a look at this whenever you get time to see what might have gone wrong.

**Comment by gridhead** [comment]
Fixed via #13.
